=head1 The Bio::Phylo libraries for phyloinformatic analysis, version 2.0

=head1 Introduction

=head1 Installation

Bio::Phylo can be installed automatically by a number of different package managers. However,
these usually rely on outdated versions, and because there is nothing that needs to be
compiled for the core installation there is no need to let a package manager do a system
wide installation, which is typically only useful for packages that include compiled
binaries and not just pure Perl source code. Bio::Phylo is pure Perl, so it is recommended 
to have the project's directory tree checked out from the source code repository 
(see Availability), and have the C<PERL5LIB> environment variable point to the C<lib> 
folder inside the directory tree. This way all functionality will be available in user 
scripts, and the user can update to the latest release (or skip back to any previous one) 
with a single command. 

Source code can be checked out from code repositories using the L<git|http://git-scm.org> 
tool on most common operating systems, it is outside of the scope of this document to discuss 
how this is done: good documentation for C<git> can be found online. How to update an 
environment variable to add an additional location to it, on any particular operating system,
is likewise best searched for online. \cite{foo}

Having said that, Bio::Phylo is also available from CPAN, which means that any tools built
around this system will be able to install the latest release, for example using the 
standard command line program C<cpan>, which is installed on almost any computer that has
C<perl> installed. Experienced Perl users commonly install the non-standard package 
management tool C<cpanm> (CPAN-minus, a play on the name of a previous tool called CPAN-plus), 
which is somewhat more user friendly, and it can install modules directly from GitHub (but 
then it will do a system-wide install that from that moment on cannot be updated from GitHub, 
so it is still better to check out the code as described above).

=head1 Core applications

=head2 Simulation

=head2 Data management

=head1 Extended functionality

=head2 Visualization

=head2 NeXML management

=head2 Compiled extensions

=head2 Likelihood calculations

=head2 Database mappings

=head1 Internal design

=head1 Availability

The latest revisions of the source code are available from the source code repository at
L<http://github.com/rvosa/bio-phylo>. The latest stable release version, which is usually 
considerably far behind the latest source code revision, is available from the Comprehensive
Perl Archive Network (CPAN) at L<http://search.cpan.org/dist/Bio-Phylo>. Accompanying this
publication is a uniquely identifiable release, stamped with a Digital Object
Identifier (DOI) issued by L<Zenodo.org>: C<doi:10.5281/zenodo.tbd>.

As is a common convention in Perl software releases, a dual licensing scheme applies to
Bio::Phylo - both the L<Artistic License|https://github.com/rvosa/bio-phylo/blob/master/COPYING>
as well as the L<GNU General Public License|https://github.com/rvosa/bio-phylo/blob/master/LICENSE>
applies. This is generally interpreted to mean that you are free to choose whichever of these
licenses fits best with your own project, should you want to reuse all (or part) of Bio::Phylo.
This is certainly the spirit: feel free to use these libraries however you see fit. 
No warranties.

=head1 Acknowledgements

=head1 References
