=head1 The Bio::Phylo libraries for phyloinformatic analysis, version 2.0

=head1 Introduction

=head1 Installation

=head1 Core applications

=head2 Simulation

=head2 Data management

=head1 Extended functionality

=head2 Visualization

=head2 NeXML management

=head2 XS compiled extensions

=head2 Object-relational mappings

=head1 Internal design

=head1 Availability

The latest revisions of the source code are available from the source code repository at
L<http://github.com/rvosa/bio-phylo>. The latest stable release version, which is usually 
considerably far behind the latest source code revision, is available from the Comprehensive
Perl Archive Network (CPAN) at L<http://search.cpan.org/dist/Bio-Phylo>. Accompanying this
publication is a uniquely identifiable release, stamped with a Digital Object
Identifier (DOI) issued by L<Zenodo.org>: c<doi:tbd>.

=head1 Acknowledgements

=head1 References
